FROM ubuntu
ENV TEST 1
RUN rm -rf /etc/apt/apt.conf.d/docker-clean; echo 'Binary::apt::APT::Keep-Downloaded-Packages "true";' > /etc/apt/apt.conf.d/keep-cache
RUN apt update -yq \
    && apt-get --no-install-recommends install -yq gcc build-essential \
    && rm -rf /var/lib/apt/* /var/cache/apt/*