build_nocached:
	DOCKER_BUILDKIT=1 docker build --progress=plain -f Dockerfile.nocached -t python-demo:nocached .

build_cached:
	DOCKER_BUILDKIT=1 docker build --progress=plain -t python-demo:cached .